import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import AppTable from "../components/AppTable"
import CreateAppForm from "../components/CreateAppForm"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <section className = "bg-blood-red">
      <Head>
        <title>Hey, Dude!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className = 'py-5' >
        <h1 className = 'text-xl md:text-5xl text-center font-bold py-10 text-gray-100'>Hey Dude!</h1>
        <p className = 'text-center text-gray-100'>Remind (and annoy) your friends about the legendary gaming session you've planned.</p>
        <div className = "container mx-auto flex justify-between py-5">
          <div className = "left flex gap-3">
            <button className = "flex bg-indigo-500 text-white px-4 py-2 rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">
              Create Session 
            </button>
          </div>
        </div>
        
        <div className="container mx-auto">
          <CreateAppForm></CreateAppForm>
        </div>

        <div className="container mx-auto bg-blood-red">
        <AppTable></AppTable>
        ok ty
        </div>
        ok ty
      </main>
        ok ty
    </section>
  )
}
