import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {BiUserPlus} from 'react-icons/bi'
import AppTable from "../components/AppTable"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <section>
      <Head>
        <title>Hey, Dude!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className = 'py-5'>
        <h1 className = 'text-xl md:text-5xl text-center font-bold py-10'>Hey Dude!</h1>
        <p className = 'text-center'>Plan a Session</p>
        <div className = "container mx-auto flex justify-between py-5 border-b">
          <div className = "left flex gap-3">
            <button className = "flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">
              Create Session <span className = 'px-1'><BiUserPlus size = {23}></BiUserPlus></span>
            </button>

          </div>
        </div>
        
        <AppTable></AppTable>

      </main>
    </section>
  )
}
